jsonCallback({
    "returnCode": "0",
    "returnMessage": null,
    "beans": [
        {
            "menuId":"2000",
            "menuName":"示例",
            "secondMenu":[
                {
                    "menuId":"20002",
                    "menuName":"参考示例",
                    "thirdMenu":[
                        {
                            "menuId":"200025",
                            "menuName":"Here多页面示例^-^!!!",
                            "url":"http://localhost:8892/ngchnl/src/module/example/mutiPageDemo.html",
                            "menuFlag":"1",
                            "openModule":"N"
                        },
                        {
                            "menuId":"200026",
                            "menuName":"单页面示例",
                            "url":"http://localhost:9010/ngchnl/gate.html#js/example/exampleNewComponent",
                            "menuFlag":"1",
                            "openModule":"N"
                        }, 
                        {
                            "menuId":"200032",
                            "menuName":"selectList示例",
                            "url":"http://localhost:9010/ngchnl/src/module/example/exampleTest.html",
                            "menuFlag":"1",
                            "openModule":"N"
                        },
                        {
                            "menuId":"200033",
                            "menuName":"chart示例",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/chart.html",
                            "menuFlag":"1",
                            "openModule":"N"
                        },
                        {
                            "menuId":"200034",
                            "menuName":"common示例",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/commonTest.html"
                        },
                        {
                            "menuId":"200035",
                            "menuName":"export示例",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/export.html"
                        },
                        {
                            "menuId":"200036",
                            "menuName":"键盘点击事件(keyboardEvent)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/keyboardEvent.html"
                        },
                        {
                            "menuId":"200037",
                            "menuName":"多层弹框示例",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/moreDialog.html"
                        }
                    ]
                },
                {
                    "menuId":"20000",
                    "menuName":"公用库示例",
                    "thirdMenu":[
                        {
                            "menuId":"200000",
                            "menuName":"ajax示例",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/ajax.html"
                        },
                        {
                            "menuId":"200001",
                            "menuName":"formAmd示例",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/formAmd.html"
                        }
                    ]
                },
                {
                    "menuId":"20001",
                    "menuName":"组件示例",
                    "thirdMenu":[
                        {
                            "menuId":"200002",
                            "menuName":"按钮组(buttonGroup)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/buttonGroup.html"
                        },
                        {
                            "menuId":"200003",
                            "menuName":"步进器(counter)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/counter.html"
                        },
                        {
                            "menuId":"200004",
                            "menuName":"日期(date)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/date.html"
                        },
                        {
                            "menuId":"200005",
                            "menuName":"详情表单(detailPanel)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/detailPanel.html"
                        },
                        {
                            "menuId":"200006",
                            "menuName":"对话框(dialog)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/dialogTest.html"
                        },
                        {
                            "menuId":"200007",
                            "menuName":"编辑器(editor)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/editor.html"
                        },
                        {
                            "menuId":"200008",
                            "menuName":"查询表单(groupSearchForm)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/groupSearchForm.html"
                        },
                        {
                            "menuId":"200009",
                            "menuName":"数据列表(list)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/list.html"
                        },
                        {
                            "menuId":"200010",
                            "menuName":"正在加载(loading)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/loading.html"
                        },
                        {
                            "menuId":"200011",
                            "menuName":"步骤条(process)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/process.html"
                        },
                        {
                            "menuId":"200012",
                            "menuName":"星级(satisfyStar)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/satisfyStar.html"
                        },
                        {
                            "menuId":"200013",
                            "menuName":"下拉框(select)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/select.html"
                        },
                        {
                            "menuId":"200014",
                            "menuName":"弹出列表(selectList)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/selectList.html"
                        },
                        {
                            "menuId":"200016",
                            "menuName":"弹出树(selectTree)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/selectTree.html"
                        },
                        {
                            "menuId":"200017",
                            "menuName":"树(simpleTree)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/simpleTree.html"
                        },
                        {
                            "menuId":"200018",
                            "menuName":"选项卡(tab)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/tab.html"
                        },
                        {
                            "menuId":"200019",
                            "menuName":"嵌套选项卡(tab)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/tabTest.html"
                        },
                        {
                            "menuId":"200020",
                            "menuName":"计时器(timer)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/timer.html"
                        },
                        {
                            "menuId":"200021",
                            "menuName":"表单验证(validator)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/validator.html"
                        },
                        {
                            "menuId":"200023",
                            "menuName":"音频(voice)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/voice.html"
                        },
                        {
                            "menuId":"200024",
                            "menuName":"组件综合示例(example)",
                            "url":"http://localhost:9010/ngchnl/src/module/example/components/mutiPageDemo.html"
                        }
                    ]
                },
                
            ]
        }
    ]
});
